// Generated by gencpp from file path_planning/velocity.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_MESSAGE_VELOCITY_H
#define PATH_PLANNING_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planning
{
template <class ContainerAllocator>
struct velocity_
{
  typedef velocity_<ContainerAllocator> Type;

  velocity_()
    : v_x(0.0)
    , v_y(0.0)
    , reverse(false)  {
    }
  velocity_(const ContainerAllocator& _alloc)
    : v_x(0.0)
    , v_y(0.0)
    , reverse(false)  {
  (void)_alloc;
    }



   typedef float _v_x_type;
  _v_x_type v_x;

   typedef float _v_y_type;
  _v_y_type v_y;

   typedef uint8_t _reverse_type;
  _reverse_type reverse;





  typedef boost::shared_ptr< ::path_planning::velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planning::velocity_<ContainerAllocator> const> ConstPtr;

}; // struct velocity_

typedef ::path_planning::velocity_<std::allocator<void> > velocity;

typedef boost::shared_ptr< ::path_planning::velocity > velocityPtr;
typedef boost::shared_ptr< ::path_planning::velocity const> velocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planning::velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planning::velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'path_planning': ['/home/chen/control_ws/src/path_planning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planning::velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning::velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning::velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning::velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning::velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning::velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planning::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06185deaaeca232469e4f80f9ff51b48";
  }

  static const char* value(const ::path_planning::velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06185deaaeca2324ULL;
  static const uint64_t static_value2 = 0x69e4f80f9ff51b48ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planning::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planning/velocity";
  }

  static const char* value(const ::path_planning::velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planning::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 v_x\n\
float32 v_y\n\
bool reverse\n\
\n\
";
  }

  static const char* value(const ::path_planning::velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planning::velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_x);
      stream.next(m.v_y);
      stream.next(m.reverse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planning::velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planning::velocity_<ContainerAllocator>& v)
  {
    s << indent << "v_x: ";
    Printer<float>::stream(s, indent + "  ", v.v_x);
    s << indent << "v_y: ";
    Printer<float>::stream(s, indent + "  ", v.v_y);
    s << indent << "reverse: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reverse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNING_MESSAGE_VELOCITY_H
